### ISSUE TITLE
App crashes when you set a directory.

### ISSUE THREAD

**Issue by kena006** [rafaelvcaetano/melonDS-android#582]
Device model: XE500C13-K03US
Android version: 9
MelonDS version: Beta 1.6.0 PS

Problem:
I set a directory to search ROM's and then it crashes 2 seconds later.
and when I open the app back up all the games appear and then it crashes!
And when I load a game ( In time before it crashes ) it reloads the app and then crashes!

Steps to reproduce:
1. Open the app on version Beta 1.6.0
2. Set directory

**Comment by kena006** [comment]
I installed version 1.5.0 the game loaded, but it was really slow. PLEASE OPTIMIZE YOUR APP. and add support for games that are meant to be held like a book. like brain age and rhythm heaven.

**Comment by Gamemulatorer** [comment]
What's your phone specifications especially GPU & CPU?

**Comment by rafaelvcaetano** [comment]
You most likely have 7z files inside the directory you chose and there is a problem in the Beta 1.6.0 version that can crash the app when processing large 7z files. I'm working on this issue and I hope to release a fix this week. This doesn't happen in version Beta 1.5.0 because there's no 7z support in that version.

> I installed version 1.5.0 the game loaded, but it was really slow

melonDS was simply designed to be more accurate, which requires more resources. Performance will eventually increase as small improvements are added, but, unfortunately, there's nothing that can be done immediately.

> and add support for games that are meant to be held like a book. like brain age and rhythm heaven.

You should be able to do that on mobile devices without a problem. But it looks like you are running melonDS on a Chromebook. I've never used one, so I'm not aware of its features. If it offers the option to simulate a device rotation, you can try to simulate a rotation to landscape mode and then create a custom layout. In its properties, set the orientation to Portrait. This should, in theory, display the content as if you were holding a Nintendo DS sideways. If Chromebooks don't have such an option, let me know and I'll see what I can do.

**Comment by kena006** [comment]
Version 1.6.1 solved my issue. Thank you for fixing it so fast! now just work on optimizing it for 32 bit/older devices.
