### ISSUE TITLE
Some Enchantments Request :D

### ISSUE THREAD

**Issue by Bittu2002** [rafaelvcaetano/melonDS-android#621]
• A Button That Swap Screens
• Update The Icon Of App , Make it More Minimalist
• Remove Unnecessary Files And Codes ( Once After 3-4 Updates )
• A button In Pause Menu To Take Screenshot Of Game (Both Screen In one Pic)
• Backup Settings And Game Save Files Into Google Drive
• Add Cheat Database Inbuilt
• Improve Performance So That Gaming Run Smooth 60fps In Processor Like MediaTek G80 , SD662
• Support For Upscaling 3D Graphics To 2x For Flagship Processors
• Make Game Shortcut To Launcher Of Android ( Tapping the shortcut Directly Open MelonDs And The Specific Game )
• Option To change Accent Colors In Android 11 and Blow
• Please Don't Chance Stock Android App Feel Of Melon Ds That is Present Right Now : ) 
• If You need Any help ! I Help ok ( don't know programming but I help in File management, Icon Designing, Ideas Etc.

Sorry I Write Too Much :P

**Comment by rafaelvcaetano** [comment]
Thanks for your suggestions! I'll try to address each one individually:

> **A Button That Swap Screens** 

This is already implemented. However, the button is not available in the default layout. You can create a custom layout and add that button.

> **Update The Icon Of App , Make it More Minimalist**

It's currently using melonDS's logo, which I don't want to change. The only thing I could modify would be the background color, but any other color would look weird due to the logo's outline.

> **Remove Unnecessary Files And Codes ( Once After 3-4 Updates )**

There are no unnecessary files in the project. Anything that is no longer used is immediately deleted.

> **A button In Pause Menu To Take Screenshot Of Game (Both Screen In one Pic)**

This might be useful. I'll add this to my TODO list.

> **Backup Settings And Game Save Files Into Google Drive**

This was already suggested by another user and it's planned (#277).

> **Add Cheat Database Inbuilt**

Adding a built-in cheat database would increase the app's download size considerably, which I want to avoid. If I find a database that is compact enough and with an appropriate license, I might add it.

> **Improve Performance So That Gaming Run Smooth 60fps In Processor Like MediaTek G80 , SD662**

Improvements are bound to be added as the development goes on. Unfortunately, it's not something that can be addressed immediately.

> **Support For Upscaling 3D Graphics To 2x For Flagship Processors**

This feature will be implemented together with the OpenGL renderer.

> **Make Game Shortcut To Launcher Of Android ( Tapping the shortcut Directly Open MelonDs And The Specific Game )**

This feature is already available. You can find these shortcuts in the device's widget list, by long pressing on the home screen.

> **Option To change Accent Colors In Android 11 and Blow**

Seems like a lot of work for a feature with low value. I'll consider this bug I won't promise anything.

> **Please Don't Chance Stock Android App Feel Of Melon Ds That is Present Right Now : )**

I don't intend to :)

**Comment by Bittu2002** [comment]
Thanks For Replaying ! World Needs Developers Like You ❤
