### ISSUE TITLE
'null cannot be cast to non-null type kotlin.String' while running ./gradlew :app:assembleGitHubRelease

### ISSUE THREAD

**Issue by RaichuBender** [rafaelvcaetano/melonDS-android#701]
#### Description
Unable to build app from master (at the time of writing this) as well as latest release code base.
#### Log
```
❯ ./gradlew :app:assembleGitHubRelease                               
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true

FAILURE: Build failed with an exception.

* Where:
Build file '/home/thomas/gitrepos/melonDS-android-beta-1.6.1/app/build.gradle.kts' line: 15

* What went wrong:
null cannot be cast to non-null type kotlin.String

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
6 actionable tasks: 6 up-to-date
```
app/build.gradle.kts:
```kts
// (...)

android {
    signingConfigs {
        create("release") {
            val props = gradleLocalProperties(rootDir)
            storeFile = file(props["MELONDS_KEYSTORE"] as String)        // <-- line giving error
            storePassword = props["MELONDS_KEYSTORE_PASSWORD"] as String
            keyAlias = props["MELONDS_KEY_ALIAS"] as String
            keyPassword = props["MELONDS_KEY_PASSWORD"] as String
        }
    }

// (...)
```
I have the latest android SDK/NDK and CMAKE installed
Am I missing something here?
Help is appreciated!

**Comment by rafaelvcaetano** [comment]
The problem is that you need to use a keystore to sign release builds. If you don't want to make release builds, you can generate debug builds like this:

`./gradlew :app:assembleGitHubDebug`

If you really want to generate release builds, you need to create a keystore and populate the `local.properties` file (which should be inside the project's root directory) with the following fields:

```
MELONDS_KEYSTORE=<path_to_keystore>
MELONDS_KEYSTORE_PASSWORD=<keystore_password>
MELONDS_KEY_ALIAS=<key_name>
MELONDS_KEY_PASSWORD=<key_password>
```

If you've never created a keystore, you can generate one by using `keytool`, which you can find in your JDK's directory. To generate a keystore, run the following command:

`keytool -keystore <keystore_name> -genkey -alias <key_name>`

You will be prompted for a bunch of fields, in which you can put whatever you want. Just make sure that you remember the passwords. Use the proper values to fill the `local.properties` file and you should be able to create release builds.

Let me know if you still have issues.

**Comment by RaichuBender** [comment]
That did the trick! I still had to make a `local.properties` file, because kotlin kept complaining absolute NULL properties, but after adding bogus entries, it's now building.
Thanks for the help!
